# Generated by Django 4.2.5 on 2026-08-22 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mealplanner", "0003_badge_userstreak_userbadge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstreak",
            name="last_logged_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.CreateModel(
            name="DailyNutritionCheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_date", models.DateField(default=django.utils.timezone.localdate)),
                ("breakfast_completed", models.BooleanField(default=False)),
                ("lunch_completed", models.BooleanField(default=False)),
                ("dinner_completed", models.BooleanField(default=False)),
                ("water_intake_ml", models.PositiveIntegerField(default=0)),
                ("met_calorie_target", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_checkins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-log_date"],
                "unique_together": {("user", "log_date")},
            },
        ),
    ]
